services:
  borgserver:
    build:
      context: .
      platforms:
#        - "linux/arm64"
        - "linux/amd64"
    restart: always
    image: workleast/borgserver
    container_name: borgserver
    volumes:
      - ${REPO_DIR}:/backups
      - ${SSH_DIR}:/home/borg/.ssh
    ports:
      - "2022:22"
    environment:
      TZ: ${TZ}
